[workspace]
members = [
    "i_interesting_numbers",
    "h_hidden_password",
    "c_find_set",
    "b_antigo",
    "a_mountains",
    "advent",
    "algo_lib",
    "archiver",
    "listener",
    "main",
]
